# Generated by Django 4.0.3 on 2022-07-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_orderline_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qty_in_stcok',
            new_name='qty_in_stock',
        ),
    ]
