version: "3.9"

services:
    autocompany:
        image: autocompany:latest
        container_name: auto-company
        command: /start_app
        expose:
          - 8000
        env_file:
            - .env-prod
        volumes:
            - .:/usr/src/app

networks: 
  default:
    external: true
    name: service-network