# Generated by Django 4.0.3 on 2022-07-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=180)),
                ('product_name', models.CharField(max_length=180)),
                ('unit_price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=180)),
                ('company', models.CharField(max_length=180)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
