# Generated by Django 4.0.3 on 2023-10-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "items",
                    models.ManyToManyField(
                        related_name="cart_product", to="products.product"
                    ),
                ),
            ],
        ),
    ]
