# Generated by Django 4.0.3 on 2023-10-15 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0003_alter_cart_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="customer",
        ),
    ]
