# Generated by Django 4.0.3 on 2023-10-15 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0004_remove_cart_customer"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="cart",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="carts.cart"
            ),
        ),
    ]
