# Generated by Django 4.0.3 on 2023-10-15 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0005_cartentry_order_id_alter_cartentry_cart_id"),
        ("customers", "0002_customer_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="cart",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to="carts.cart",
            ),
        ),
    ]
