# Generated by Django 4.0.3 on 2024-01-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpartsapi', '0003_rename_stock_product_available_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed')], default='CONFIRMED', max_length=100),
        ),
    ]
