# Generated by Django 4.0.3 on 2023-10-14 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateTimeField()),
                ('cart_entries', models.ManyToManyField(to='carts.cartentry')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.customer')),
            ],
        ),
    ]
