# Generated by Django 4.0.3 on 2023-10-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateTimeField()),
                ('items', models.ManyToManyField(related_name='order_product', to='products.product')),
            ],
        ),
    ]
