# Generated by Django 4.0.3 on 2023-10-15 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="cart_entries",
        ),
    ]
