# Generated by Django 4.0.3 on 2022-07-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapi', '0002_cartitems_delete_cartdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
