# Generated by Django 4.0.3 on 2022-07-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapi', '0003_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.IntegerField(null=True),
        ),
    ]
