# Generated by Django 4.0.3 on 2022-07-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapi', '0004_alter_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='quantity',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
