# Generated by Django 4.0.3 on 2022-07-02 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapi', '0006_remove_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='carapi.cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_info',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('DELIVERY', 'Delivery')], default='CONFIRMED', max_length=100),
        ),
    ]
