# Generated by Django 4.0.3 on 2022-05-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='name',
        ),
    ]
