# Generated by Django 4.0.3 on 2022-05-29 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_localuser_remove_cart_created_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocalUser',
            new_name='NewUser',
        ),
    ]
