# Generated by Django 4.0.3 on 2022-05-29 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_localuser_newuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.newuser'),
        ),
    ]
